const applicationConfigRouter = require('./applicationConfig')
const appManageRouter = require('./appManage')
const companyRouter = require('./company')
const flowDataInfoRouter = require('./flowDataInfoByHour')
const flowDataInfoByDayRouter = require('./flowDataInfoByDay')
const teamRouter = require('./team')
const userRouter = require('./user')
const userTokenRouter = require('./userToken')
const ProductRouter = require('./product')
const OrderRouter = require('./orderInfo')
const ssoRouter = require('./sso')
const alarmListRouter = require('./alarmList')
const noticeTemplateRouter = require('./noticeTemplate')
const alarmRuleRouter = require('./alarmRule')
const alarmOverviewRouter = require('./alarmOverview')
const orderRouter = require('./orderInfo')
const menuPermissionsRouter = require('./menuPermissions')
const projectSynchronizationRouter = require('./projectSynchronization')
const functionSynchronizationRouter = require('./functionSynchronization')
const reportTemplateRouter = require('./reportTemplate')
const reportTaskRouter = require('./reportTask')
const generatedReportRouter = require('./generatedReport')
const schemaSyncRouter = require('./schemaSync')
const createRouter = (router) => {
  applicationConfigRouter(router)
  appManageRouter(router)
  companyRouter(router)
  flowDataInfoByDayRouter(router)
  flowDataInfoRouter(router)
  teamRouter(router)
  userRouter(router)
  userTokenRouter(router)
  ProductRouter(router)
  OrderRouter(router)
  ssoRouter(router)
  alarmListRouter(router)
  noticeTemplateRouter(router)
  alarmRuleRouter(router)
  alarmOverviewRouter(router)
  orderRouter(router)
  menuPermissionsRouter(router)
  projectSynchronizationRouter(router)
  functionSynchronizationRouter(router)
  reportTaskRouter(router)
  reportTemplateRouter(router)
  generatedReportRouter(router)
  schemaSyncRouter(router)
}
module.exports = {
  createRouter
}