module.exports = [
    "../schema/customerPV",
    "../schema/behaviorInfo",
    "../schema/customerPvLeave",
    "../schema/customerStayTime",
    "../schema/extendBehaviorInfo",
    "../schema/HttpErrorInfo",
    "../schema/HttpLogInfo.js",
    "../schema/HttpLogReqInfo",
    "../schema/javascriptErrorInfo",
    "../schema/pageLoadInfo",
    "../schema/screenShotInfo",
    "../schema/pageLoadInfoByMinute",
    "../schema/resourceLoadInfo",
    "../schema/resourcePerfInfo",
    "../schema/infoCountByDay",
    "../schema/infoCountByHour",
    "../schema/deviceInfoCountByDay",
    "../schema/deviceInfoCountByHour",
    "../schema/jsErrorHandleList",
    "../schema/httpErrorHandleList",
    "../schema/loadTimeInfoByHour",
    "../schema/videoLog",
    "../schema/localLog",
    // 移动端性能监控表
    "../schema/mobilePerformanceLog",
    "../schema/mobileErrorLog",
]
