//为每个项目创建一个心跳次数卡片
module.exports = [
    {
        "pageId":279,
        "name": "看板描述信息",
        "type": 8,
        "calcRule":"[]",
        "sort": 1,
        "conversionCycle": 0,
        "groupByFlag": 0,
        "chartTableShow": "",
        "togetherList": "",
        "refreshFrequency": 0,
        "isShowOnlineCount": 0,
        "dataGrid": "{\"w\":12,\"h\":1,\"x\":0,\"y\":0,\"i\":\"662a7480-73e8-11ef-b64c-09ccec97c0e9\",\"minH\":1,\"moved\":false,\"static\":false}",
        "describe": "这个看板主要用于记录PV、UV、新用户、停留时间、地理位置、访问top信息等",
        "createBy":"webfunny",
        "updateBy":null
    },
    {
        "pageId":279,
        "name": "当日访问量",
        "type": 6,
        "calcRule":"[{\"calcName\":\"人数\",\"unit\":\"人\",\"alarmId\":\"\",\"prePoint\":{\"calcField\":{\"fieldName\":\"weCustomerKey\",\"isRepeat\":\"0\"},\"pointId\":269,\"queryCriteria\":[]},\"calcNameKey\":\"renshu20240916130849\"}]",
        "sort": 4,
        "conversionCycle": 0,
        "groupByFlag": 0,
        "chartTableShow": "",
        "togetherList": "total,average,yoyRatio,ringRatio",
        "refreshFrequency": 0,
        "isShowOnlineCount": 0,
        "dataGrid": "{\"w\":3,\"h\":4,\"x\":0,\"y\":1,\"i\":\"c22d2f10-73e9-11ef-9c5d-170073a05070\",\"minH\":1,\"moved\":false,\"static\":false}",
        "describe": "",
        "createBy":"webfunny",
        "updateBy":null
    },
    {
        "pageId":279,
        "name": "当日访问人数",
        "type": 6,
        "calcRule":"[{\"calcName\":\"人数\",\"alarmId\":\"\",\"prePoint\":{\"calcField\":{\"fieldName\":\"weCustomerKey\",\"isRepeat\":\"1\"},\"pointId\":269,\"queryCriteria\":[]},\"calcNameKey\":\"renshu20240916130922\"}]",
        "sort": 7,
        "conversionCycle": 0,
        "groupByFlag": 0,
        "chartTableShow": "",
        "togetherList": "total,average,yoyRatio,ringRatio",
        "refreshFrequency": 0,
        "isShowOnlineCount": 0,
        "dataGrid": "{\"w\":3,\"h\":4,\"x\":3,\"y\":1,\"i\":\"d6281520-73e9-11ef-9c5d-170073a05070\",\"minH\":1,\"moved\":false,\"static\":false}",
        "describe": "",
        "createBy":"webfunny",
        "updateBy":null
    },
    {
        "pageId":279,
        "name": "当日新用户",
        "type": 6,
        "calcRule":"[{\"calcName\":\"人数\",\"unit\":\"次\",\"alarmId\":\"\",\"prePoint\":{\"calcField\":{\"fieldName\":\"weCustomerKey\",\"isRepeat\":\"1\"},\"pointId\":269,\"queryCriteria\":[{\"fieldName\":\"weNewStatus\",\"rule\":\"等于\",\"value\":\"1\"}]},\"calcNameKey\":\"renshu20240916131005\"}]",
        "sort": 10,
        "conversionCycle": 0,
        "groupByFlag": 0,
        "chartTableShow": "",
        "togetherList": "total,average,yoyRatio,ringRatio",
        "refreshFrequency": 0,
        "isShowOnlineCount": 0,
        "dataGrid": "{\"w\":3,\"h\":4,\"x\":6,\"y\":1,\"i\":\"efc8e770-73e9-11ef-9c5d-170073a05070\",\"minH\":1,\"moved\":false,\"static\":false}",
        "describe": "",
        "createBy":"webfunny",
        "updateBy":null
    },
    {
        "pageId":279,
        "name": "当日平均停留时长(秒)",
        "type": 6,
        "calcRule":"[{\"calcName\":\"时间\",\"unit\":\"s\",\"alarmId\":\"\",\"prePoint\":{\"calcField\":{\"fieldName\":\"stayTime\",\"isRepeat\":\"2\"},\"pointId\":241,\"queryCriteria\":[]},\"calcNameKey\":\"shijian20240916131447\",\"endPoint\":{\"calcField\":{\"fieldName\":\"weCustomerKey\",\"isRepeat\":\"1\"},\"pointId\":241,\"queryCriteria\":[]},\"calcType\":\"/\"}]",
        "sort": 13,
        "conversionCycle": 0,
        "groupByFlag": 0,
        "chartTableShow": "",
        "togetherList": "total,average,yoyRatio,ringRatio",
        "refreshFrequency": 0,
        "isShowOnlineCount": 0,
        "dataGrid": "{\"w\":3,\"h\":4,\"x\":9,\"y\":1,\"i\":\"97fdaa20-73ea-11ef-9c5d-170073a05070\",\"minH\":1,\"moved\":false,\"static\":false}",
        "describe": "",
        "createBy":"webfunny",
        "updateBy":null
    },
    {
        "pageId":279,
        "name": "用户浏览数据",
        "type": 3,
        "calcRule":"[{\"calcName\":\"访问量\",\"unit\":\"次\",\"alarmId\":\"\",\"prePoint\":{\"calcField\":{\"fieldName\":\"weCustomerKey\",\"isRepeat\":\"0\"},\"pointId\":269,\"queryCriteria\":[]},\"calcNameKey\":\"fangwenliang20240916124852\"},{\"calcName\":\"访问人数\",\"alarmId\":\"\",\"prePoint\":{\"calcField\":{\"fieldName\":\"weCustomerKey\",\"isRepeat\":\"1\"},\"pointId\":269,\"queryCriteria\":[]},\"calcNameKey\":\"fangwenrenshu20240916124852\"}]",
        "sort": 16,
        "conversionCycle": 0,
        "groupByFlag": 0,
        "chartTableShow": "",
        "togetherList": "",
        "refreshFrequency": 0,
        "isShowOnlineCount": 0,
        "dataGrid": "{\"w\":3,\"h\":4,\"x\":0,\"y\":5,\"i\":\"f8a54df0-73e6-11ef-b64c-09ccec97c0e9\",\"minH\":1,\"moved\":false,\"static\":false}",
        "describe": "",
        "createBy":"webfunny",
        "updateBy":null
    },
    {
        "pageId":279,
        "name": "用户地理位置(世界地图)",
        "type": 7,
        "calcRule":"[{\"calcName\":\"次数\",\"alarmId\":\"\",\"prePoint\":{\"calcField\":{\"fieldName\":\"weCountry\",\"isRepeat\":\"4\"},\"pointId\":269,\"queryCriteria\":[]},\"calcNameKey\":\"cishu20240916130322\"}]",
        "sort": 19,
        "conversionCycle": 0,
        "groupByFlag": 1,
        "chartTableShow": "chart-map-world",
        "togetherList": "total,average,yoyRatio,ringRatio",
        "refreshFrequency": 0,
        "isShowOnlineCount": 1,
        "dataGrid": "{\"w\":6,\"h\":9,\"x\":3,\"y\":5,\"i\":\"ff780f80-73e8-11ef-b64c-09ccec97c0e9\",\"minH\":1,\"moved\":false,\"static\":false}",
        "describe": "",
        "createBy":"webfunny",
        "updateBy":null
    },
    {
        "pageId":279,
        "name": "新用户趋势",
        "type": 1,
        "calcRule":"[{\"calcName\":\"人数\",\"unit\":\"人\",\"alarmId\":\"\",\"prePoint\":{\"calcField\":{\"fieldName\":\"weCustomerKey\",\"isRepeat\":\"1\"},\"pointId\":269,\"queryCriteria\":[{\"fieldName\":\"weNewStatus\",\"rule\":\"等于\",\"value\":\"1\"}]},\"calcNameKey\":\"renshu20240916125514\"}]",
        "sort": 25,
        "conversionCycle": 0,
        "groupByFlag": 0,
        "chartTableShow": "",
        "togetherList": "total,average,yoyRatio,ringRatio",
        "refreshFrequency": 0,
        "isShowOnlineCount": 0,
        "dataGrid": "{\"w\":3,\"h\":4,\"x\":9,\"y\":5,\"i\":\"dc48e8a0-73e7-11ef-b64c-09ccec97c0e9\",\"minH\":1,\"moved\":false,\"static\":false}",
        "describe": "",
        "createBy":"webfunny",
        "updateBy":null
    },
    {
        "pageId":279,
        "name": "页面访问Top10",
        "type": 4,
        "calcRule":"[{\"calcName\":\"访问量\",\"unit\":\"次\",\"alarmId\":\"\",\"prePoint\":{\"calcField\":{\"fieldName\":\"weAccessAddress\",\"isRepeat\":\"0\"},\"pointId\":\"257\",\"queryCriteria\":[]},\"calcNameKey\":\"fangwenliang20240918035650\"}]",
        "sort": 28,
        "conversionCycle": 0,
        "groupByFlag": 1,
        "chartTableShow": "chart-histogram",
        "togetherList": "",
        "refreshFrequency": 0,
        "isShowOnlineCount": 0,
        "dataGrid": "{\"w\":3,\"h\":5,\"x\":0,\"y\":9,\"i\":\"a5c542f0-73e8-11ef-b64c-09ccec97c0e9\",\"minH\":1,\"moved\":false,\"static\":false}",
        "describe": "",
        "createBy":"webfunny",
        "updateBy":null
    },
    {
        "pageId":279,
        "name": "页面平均停留时间(秒)",
        "type": 2,
        "calcRule":"[{\"calcName\":\"时间\",\"alarmId\":\"\",\"prePoint\":{\"calcField\":{\"fieldName\":\"stayTime\",\"isRepeat\":\"2\"},\"pointId\":241,\"queryCriteria\":[]},\"endPoint\":{\"calcField\":{\"fieldName\":\"weCustomerKey\",\"isRepeat\":\"1\"},\"pointId\":241,\"queryCriteria\":[]},\"calcType\":\"/\",\"calcNameKey\":\"shijian20240916130209\"}]",
        "sort": 37,
        "conversionCycle": 0,
        "groupByFlag": 0,
        "chartTableShow": "",
        "togetherList": "",
        "refreshFrequency": 0,
        "isShowOnlineCount": 0,
        "dataGrid": "{\"w\":3,\"h\":5,\"x\":9,\"y\":9,\"i\":\"d4102710-73e8-11ef-b64c-09ccec97c0e9\",\"minH\":1,\"moved\":false,\"static\":false}",
        "describe": "",
        "createBy":"webfunny",
        "updateBy":null
    },
    {
        "pageId":279,
        "name": "网站来源占比情况",
        "type": 4,
        "calcRule":"[{\"calcName\":\"人数\",\"unit\":\"人\",\"alarmId\":\"\",\"prePoint\":{\"calcField\":{\"fieldName\":\"weWebsitSource\",\"isRepeat\":\"5\"},\"pointId\":269,\"queryCriteria\":[]},\"calcNameKey\":\"renshu20240916132033\"}]",
        "sort": 43,
        "conversionCycle": 0,
        "groupByFlag": 1,
        "chartTableShow": "chart-pie",
        "togetherList": "total,average,yoyRatio,ringRatio",
        "refreshFrequency": 0,
        "isShowOnlineCount": 0,
        "dataGrid": "{\"w\":4,\"h\":6,\"x\":0,\"y\":14,\"i\":\"65f83990-73eb-11ef-9c5d-170073a05070\",\"minH\":1,\"moved\":false,\"static\":false}",
        "describe": "",
        "createBy":"webfunny",
        "updateBy":null
    },
    {
        "pageId":279,
        "name": "关键省份展示",
        "type": 4,
        "calcRule":"[{\"calcName\":\"人数\",\"alarmId\":\"\",\"prePoint\":{\"calcField\":{\"fieldName\":\"weProvince\",\"isRepeat\":\"5\"},\"pointId\":269,\"queryCriteria\":[]},\"calcNameKey\":\"renshu20240916132145\"}]",
        "sort": 47,
        "conversionCycle": 0,
        "groupByFlag": 1,
        "chartTableShow": "chart-words",
        "togetherList": "",
        "refreshFrequency": 0,
        "isShowOnlineCount": 0,
        "dataGrid": "{\"w\":4,\"h\":6,\"x\":4,\"y\":14,\"i\":\"911388a0-73eb-11ef-9c5d-170073a05070\",\"minH\":1,\"moved\":false,\"static\":false}",
        "describe": "",
        "createBy":"webfunny",
        "updateBy":null
    },
    {
        "pageId":279,
        "name": "页面访问量趋势图",
        "type": 4,
        "calcRule":"[{\"calcName\":\"数量\",\"unit\":\"次\",\"alarmId\":\"\",\"prePoint\":{\"calcField\":{\"fieldName\":\"wePagePath\",\"isRepeat\":\"4\"},\"pointId\":269,\"queryCriteria\":[]},\"calcNameKey\":\"shuliang20240916132438\"}]",
        "sort": 51,
        "conversionCycle": 0,
        "groupByFlag": 1,
        "chartTableShow": "chart-area",
        "togetherList": "",
        "refreshFrequency": 0,
        "isShowOnlineCount": 0,
        "dataGrid": "{\"w\":4,\"h\":6,\"x\":8,\"y\":14,\"i\":\"f83caed0-73eb-11ef-9c5d-170073a05070\",\"minH\":1,\"moved\":false,\"static\":false}",
        "describe": "",
        "createBy":"webfunny",
        "updateBy":null
    },
]