const alarmRouter = require('./alarm')
const alarmRuleRouter = require('./alarmRule')
const commonRouter = require('./common')
const commonTableRouter = require('./commonTable')
const configRouter = require('./config')
const customerPvRouter = require('./customerPv')
const customerPvLeaveRouter = require('./customerPvLeave')
const customerStayTimeRouter = require('./customerStayTime')
const extendBehaviorInfoRouter = require('./extendBehaviorInfo')
const failRouter = require('./fail')
const httpErrorHandleListRouter = require('./httpErrorHandleList')
const httpErrorInfoRouter = require('./httpErrorInfo')
const httpLogInfoRouter = require('./httpLogInfo')
const ignoreErrorRouter = require('./ignoreError')
const javascriptErrorInfoRouter = require('./javascriptErrorInfo')
const jsErrorHandleListRouter = require('./jsErrorHandleList')
const messageRouter = require('./message')
const pageLoadInfoRouter = require('./pageLoadInfo')
const projectRouter = require('./project')
const resourceLoadInfoRouter = require('./resourceLoadInfo')
const resourcePerfInfoRouter = require('./resourcePerfInfo')
const videoLogRouter = require('./videoLog')
const videosRouter = require('./videos')
const customerStatusRouter = require('./customerStatus')
const localLogRouter = require('./localLog')
const thirdPartyRouter = require('./thirdParty')
const dataOverviewForCenterRouter = require('./dataOverviewForCenter')
const overviewNewRouter = require('./overviewNew')
const schemaSyncRouter = require('./schemaSync')
const logSearchRouter = require('./logSearch')
const topologyRouter = require('./topology')
// walkingfunny相关接口，统一管理
const walkingfunnyRouter = require('./walkingfunny')

const createRouter = (router) => {
  alarmRouter(router)
  alarmRuleRouter(router)
  commonRouter(router)
  commonTableRouter(router)
  configRouter(router)
  customerPvRouter(router)
  customerPvLeaveRouter(router)
  customerStayTimeRouter(router)
  extendBehaviorInfoRouter(router)
  failRouter(router)
  httpErrorHandleListRouter(router)
  httpErrorInfoRouter(router)
  httpLogInfoRouter(router)
  ignoreErrorRouter(router)
  javascriptErrorInfoRouter(router)
  jsErrorHandleListRouter(router)
  messageRouter(router)
  pageLoadInfoRouter(router)
  projectRouter(router)
  resourceLoadInfoRouter(router)
  resourcePerfInfoRouter(router)
  videoLogRouter(router)
  videosRouter(router)
  customerStatusRouter(router)
  walkingfunnyRouter(router)
  localLogRouter(router)
  thirdPartyRouter(router)
  dataOverviewForCenterRouter(router)
  overviewNewRouter(router)
  logSearchRouter(router)
  schemaSyncRouter(router)
  topologyRouter(router)
}

module.exports = {
  createRouter
}
