#=================================================
# https://github.com/zhangsean/webfunny_monitor
# Description: Build and push docker image for webfunny_monitor using GitHub Actions
# License: Apache V2.0
# Author: ZhangSean
#=================================================

name: Build and push docker image

on:
  schedule:
    - cron: 1 0 * * *
  watch:
    types: [started]
    if: github.event.repository.owner.id == github.event.sender.id
  push:
    branches:
      - master

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Get latest version
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          export LATEST=$(sed -n '/version/s/.*\"\(.*\)\".*/\1/p' package.json)
          echo "LATEST=$LATEST" >> $GITHUB_ENV
          echo "Latest version: $LATEST"

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        if: success() && env.LATEST != ''
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        if: success() && env.LATEST != ''
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        if: success() && env.LATEST != ''
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        if: success() && env.LATEST != ''
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/webfunny_monitor:latest,
            ${{ secrets.DOCKERHUB_USERNAME }}/webfunny_monitor:${{ env.LATEST }}
